name: Publish documentation

on:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create commit
        run: |
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
          echo 'Next line' >> test.txt
          git add test.txt
          echo "This is the message" > /tmp/_my_message.txt
          echo >> /tmp/_my_message.txt
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git commit -F /tmp/_my_message.txt

      - name: And push it
        run: |
          git push
